In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Importation du jeu de données
import pandas as pd
data = pd.read_csv('data.csv', encoding = 'latin-1')
data

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,NaN

In [ ]:
#Liste des differentes colonnes
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [ ]:
#Description du jeu de données
data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500,NaN

In [ ]:
# suppression de la derniere colonne
del data['Unnamed: 32']
#Suppression des doublons
data.drop_duplicates(inplace = True)

In [ ]:
#Description du jeu de données
data.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000,569.000000
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,0.096360,0.104341,0.088799,0.048919,0.181162,...,16.269190,25.677223,107.261213,880.583128,0.132369,0.254265,0.272188,0.114606,0.290076,0.083946
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,0.014064,0.052813,0.079720,0.038803,0.027414,...,4.833242,6.146258,33.602542,569.356993,0.022832,0.157336,0.208624,0.065732,0.061867,0.018061
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,0.052630,0.019380,0.000000,0.000000,0.106000,...,7.930000,12.020000,50.410000,185.200000,0.071170,0.027290,0.000000,0.000000,0.156500,0.055040
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,0.086370,0.064920,0.029560,0.020310,0.161900,...,13.010000,21.080000,84.110000,515.300000,0.116600,0.147200,0.114500,0.064930,0.250400,0.071460
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,0.095870,0.092630,0.061540,0.033500,0.179200,...,14.970000,25.410000,97.660000,686.500000,0.131300,0.211900,0.226700,0.099930,0.282200,0.080040
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,0.105300,0.130400,0.130700,0.074000,0.195700,...,18.790000,29.720000,125.400000,1084.000000,0.146000,0.339100,0.382900,0.161400,0.317900,0.092080
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,0.163400,0.345400,0.426800,0.201200,0.304000,...,36.040000,49.540000,251.200000,4254.000000,0.222600,1.058000,1.252000,0.291000,0.663800,0.207500

In [ ]:
# X = data.iloc[:, 2:]   pour avoir le dataset des features
#pour le reseau de neurones ce sont les valeurs de la dataset des features qui nous interesse 
#Recuperer les valeurs des features 
X = data.iloc[:, 2:].values
X = pd.DataFrame(X)
X

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

In [ ]:
#Recuperer la target
#y = data.iloc[:, 1]
#Recuperer les valeurs de la target
y = data.iloc[:, 1].values
y = pd.DataFrame(y)
y

     0
0    M
1    M
2    M
3    M
4    M
..  ..
564  M
565  M
566  M
567  M
568  B

[569 rows x 1 columns]

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
y = labelencoder_X_1.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [ ]:
ligne, colonne = X_train.shape
#print(X_train.shape[0])
print("ligne : ", ligne, "\ncolonne : ", colonne)

ligne :  512
colonne :  30

In [ ]:
ligne, colonne = X_test.shape
#print(X_test.shape[0])
print("ligne : ", ligne, "\ncolonne : ", colonne)

ligne :  57
colonne :  30

In [ ]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

In [ ]:
# Initialising the ANN(Artificial Neural Netword)
classifier = Sequential()

In [ ]:
#deux couches cachees de 16 neurones par couche cachee et un neuron pour la couche de sortie
sizes = [16, 16, 1]

In [ ]:
# Models 
# premiere couche cachee
Momentum = Sequential([Dense(units=sizes[0], input_dim=X_train.shape[1], activation='relu')])
Nag = Sequential([Dense(units=sizes[0], input_dim=X_train.shape[1], activation='relu')])
Adagrad = Sequential([Dense(units=sizes[0], input_dim=X_train.shape[1], activation='relu')])
Adadelta = Sequential([Dense(units=sizes[0], input_dim=X_train.shape[1], activation='relu')])
RMSProp = Sequential([Dense(units=sizes[0], input_dim=X_train.shape[1], activation='relu')])
Adam = Sequential([Dense(units=sizes[0], input_dim=X_train.shape[1], activation='relu')])

In [ ]:
# Ajout des couches
for i in range(1, len(sizes)-1):
    Momentum.add(Dense(units=sizes[i], activation='relu'))
    Nag.add(Dense(units=sizes[i], activation='relu'))
    Adagrad.add(Dense(units=sizes[i], activation='relu'))
    Adadelta.add(Dense(units=sizes[i], activation='relu'))
    RMSProp.add(Dense(units=sizes[i], activation='relu'))
    Adam.add(Dense(units=sizes[i], activation='relu'))

In [ ]:
# Couche de sortie    
Momentum.add(Dense(units=sizes[-1], activation='sigmoid'))
Nag.add(Dense(units=sizes[-1], activation='sigmoid'))
Adagrad.add(Dense(units=sizes[-1], activation='sigmoid'))
Adadelta.add(Dense(units=sizes[-1], activation='sigmoid'))
RMSProp.add(Dense(units=sizes[-1], activation='sigmoid'))
Adam.add(Dense(units=sizes[-1], activation='sigmoid'))

In [ ]:
layers_sizes = [X_train.shape[1], *sizes]
weigths = []
#print(len(layers_sizes))

In [ ]:
# Initialisation des poids au même endroit
for i in range(len(layers_sizes)-1):
    weigths.append(np.random.rand(layers_sizes[i], layers_sizes[i+1]))  # la matrice correspondante a la couche ou on se trouve
    weigths.append(np.random.rand(layers_sizes[i+1]))   #la liste du biais

In [ ]:
Momentum.set_weights(weigths)
Nag.set_weights(weigths)
Adagrad.set_weights(weigths)
Adadelta.set_weights(weigths)
RMSProp.set_weights(weigths)
Adam.set_weights(weigths)

batch_sizes = 20
epochs = 5

In [ ]:
Momentun_optimizer = tf.keras.optimizers.SGD(
    learning_rate=0.01,
    momentum=0.1,
    nesterov=False,
    name='SGD',
)
# Compiling the ANN
Momentum.compile(optimizer=Momentun_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
# Fitting the ANN to the Training set
Momentum.fit(X_train, y_train, batch_size=batch_sizes, epochs=epochs)

Epoch 1/5
26/26 [==============================] - 0s 2ms/step - loss: 10.7221 - accuracy: 0.3672
Epoch 2/5
26/26 [==============================] - 0s 2ms/step - loss: 8.9797 - accuracy: 0.3652
Epoch 3/5
26/26 [==============================] - 0s 2ms/step - loss: 7.3507 - accuracy: 0.4219
Epoch 4/5
26/26 [==============================] - 0s 2ms/step - loss: 4.6746 - accuracy: 0.5195
Epoch 5/5
26/26 [==============================] - 0s 2ms/step - loss: 3.1887 - accuracy: 0.6816

In [ ]:
Nag_optimizer = tf.keras.optimizers.SGD(
    learning_rate=0.01,
    momentum=0.1,
    nesterov=True,
    name='SGD',
)
# Compiling the ANN
Nag.compile(optimizer=Momentun_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
# Fitting the ANN to the Training set
Nag.fit(X_train, y_train, batch_size=batch_sizes, epochs=epochs)

Epoch 1/5
26/26 [==============================] - 1s 2ms/step - loss: 8.6798 - accuracy: 0.3672
Epoch 2/5
26/26 [==============================] - 0s 2ms/step - loss: 9.8590 - accuracy: 0.3555
Epoch 3/5
26/26 [==============================] - 0s 2ms/step - loss: 10.1237 - accuracy: 0.3770
Epoch 4/5
26/26 [==============================] - 0s 2ms/step - loss: 4.8568 - accuracy: 0.5469
Epoch 5/5
26/26 [==============================] - 0s 2ms/step - loss: 4.6503 - accuracy: 0.6328

In [ ]:
Adagrad_optimizer = tf.keras.optimizers.Adagrad(
    learning_rate=0.01,
    initial_accumulator_value=0.1,
    epsilon=1e-07,
    name='Adagrad',
)
# Compiling the ANN
Adagrad.compile(optimizer=Adagrad_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
# Fitting the ANN to the Training set
Adagrad.fit(X_train, y_train, batch_size=batch_sizes, epochs=epochs)

Epoch 1/5
26/26 [==============================] - 1s 2ms/step - loss: 19.9848 - accuracy: 0.3711
Epoch 2/5
26/26 [==============================] - 0s 2ms/step - loss: 14.8924 - accuracy: 0.3711
Epoch 3/5
26/26 [==============================] - 0s 2ms/step - loss: 12.3872 - accuracy: 0.3711
Epoch 4/5
26/26 [==============================] - 0s 2ms/step - loss: 10.6909 - accuracy: 0.3711
Epoch 5/5
26/26 [==============================] - 0s 2ms/step - loss: 9.3719 - accuracy: 0.3711

In [ ]:
tf.keras.optimizers.Adadelta(
    learning_rate=0.01,
    rho=0.95,
    epsilon=1e-07,
    name='Adadelta',
)
# Compiling the ANN
Adadelta.compile(optimizer=Adagrad_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
# Fitting the ANN to the Training set
Adadelta.fit(X_train, y_train, batch_size=batch_sizes, epochs=epochs)

Epoch 1/5
26/26 [==============================] - 1s 2ms/step - loss: 19.6939 - accuracy: 0.3711
Epoch 2/5
26/26 [==============================] - 0s 2ms/step - loss: 14.5059 - accuracy: 0.3711
Epoch 3/5
26/26 [==============================] - 0s 2ms/step - loss: 12.0612 - accuracy: 0.3711
Epoch 4/5
26/26 [==============================] - 0s 2ms/step - loss: 10.3922 - accuracy: 0.3711
Epoch 5/5
26/26 [==============================] - 0s 2ms/step - loss: 9.1065 - accuracy: 0.3711

In [ ]:
tf.keras.optimizers.RMSprop(
    learning_rate=0.01,
    rho=0.95,
    momentum=0.1,
    epsilon=1e-07,
    centered=False,
    name='RMSprop',
)
# Compiling the ANN
RMSProp.compile(optimizer=Adagrad_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
# Fitting the ANN to the Training set
RMSProp.fit(X_train, y_train, batch_size=batch_sizes, epochs=epochs)

Epoch 1/5
26/26 [==============================] - 1s 2ms/step - loss: 20.2836 - accuracy: 0.3711
Epoch 2/5
26/26 [==============================] - 0s 2ms/step - loss: 14.9732 - accuracy: 0.3711
Epoch 3/5
26/26 [==============================] - 0s 2ms/step - loss: 12.5079 - accuracy: 0.3711
Epoch 4/5
26/26 [==============================] - 0s 2ms/step - loss: 10.7643 - accuracy: 0.3711
Epoch 5/5
26/26 [==============================] - 0s 2ms/step - loss: 9.5055 - accuracy: 0.3711

In [ ]:
tf.keras.optimizers.Adam(
    learning_rate=0.01,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    name='Adam',
)
# Compiling the ANN
Adam.compile(optimizer=Adagrad_optimizer, loss='binary_crossentropy', metrics=['accuracy'])
# Fitting the ANN to the Training set
Adam.fit(X_train, y_train, batch_size=batch_sizes, epochs=epochs)

Epoch 1/5
26/26 [==============================] - 0s 2ms/step - loss: 20.4000 - accuracy: 0.3711
Epoch 2/5
26/26 [==============================] - 0s 2ms/step - loss: 15.3990 - accuracy: 0.3711
Epoch 3/5
26/26 [==============================] - 0s 2ms/step - loss: 12.7826 - accuracy: 0.3711
Epoch 4/5
26/26 [==============================] - 0s 2ms/step - loss: 11.0194 - accuracy: 0.3711
Epoch 5/5
26/26 [==============================] - 0s 2ms/step - loss: 9.6626 - accuracy: 0.3711

In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

ValueError: ignored

In [ ]:
print("Our accuracy is {}%".format(((cm[0][0] + cm[1][1])/57)*100))